export const ingredients = [
  'abacate',
  'abobora',
  'absenta',
  'acedera',
  'aceite',
  'aceite de canola',
  'aceite de coco',
  'aceite de germen de trigo',
  'aceite de girasol',
  'aceite de higado de bacalao',
  'aceite de oliva',
  'aceite de semillas',
  'aceite de sesamo',
  'aceituna',
  'aceituna en salmuera',
  'aceituna negra',
  'aceituna rellena de anchoa',
  'acelga',
  'achicoria',
  'achiote',
  'agua',
  'agua de azahar',
  'aguacate',
  'aguardiente',
  'ajedrea',
  'ajete',
  'aji',
  'ajo',
  'ajo molido',
  'ajonjoli',
  'ajoporro',
  'aji dulce',
  'albaricoque',
  'albaricoque seco',
  'alcachofa',
  'alcaparra',
  'alcaucil',
  'alga',
  'alga nori',
  'alga wakame',
  'alioli',
  'alita de pollo',
  'almeja',
  'almendra',
  'almendra brasileña',
  'almidon de maiz',
  'almibar',
  'alubia',
  'alubia seca',
  'amanita caesarea',
  'amaretto',
  'anacardo',
  'ananas',
  'anchoa',
  'anchoa en aceite',
  'androlla',
  'anguila',
  'anguila ahumada',
  'angelica',
  'anis',
  'anis dulce',
  'anis estrellado',
  'anis seco',
  'apio',
  'apio de raiz',
  'apricot (licor)',
  'arak',
  'aranque salado',
  'arenque',
  'arenque fresco',
  'arracacha',
  'arroz',
  'arroz basmati',
  'arroz bomba',
  'arroz inflado',
  'arroz integral',
  'arroz largo',
  'arroz redondo',
  'arroz salvaje',
  'arroz tailandes',
  'arroz tostado',
  'arroz vaporizado',
  'arugula',
  'arvejas mollares',
  'arandano',
  'atun en aceite en lata',
  'atun en escabeche',
  'atun fresco',
  'atun natural en lata',
  'auyama',
  'avellana',
  'avena',
  'azafran',
  'azucar',
  'azucar blanco',
  'azucar moreno',
  'azucar negro',
  'azucar sin refinar ',
  'bacaladilla',
  'bacalao',
  'bacalao desalado',
  'bacalao fresco',
  'bacon',
  'bagel',
  'baguette',
  'bambu',
  'banana',
  'banano',
  'barquillo',
  'barra de pan',
  'basa',
  'base de pizza',
  'batata',
  'bechamel',
  'berberecho',
  'berenjena',
  'berro',
  'berza',
  'besamel',
  'besugo',
  'betabel',
  'betarraga',
  'bicarbonato',
  'bija',
  'bistec de cerdo',
  'bizcocho',
  'bizcocho de soletilla',
  'bizcocho en laminas',
  'blue tropic',
  'boga',
  'bogavante',
  'boletus',
  'boniato',
  'bonito',
  'boqueron',
  'botillo',
  'brandy',
  'brote de soja',
  'brotola (pescado)',
  'brecol',
  'brocoli',
  'buey',
  'buey de mar',
  'burro (pescado)',
  'butifarra',
  'buttermilk',
  'benedictine',
  'cabrito',
  'cacahuete',
  'cacao',
  'cacao en polvo',
  'cachaza ',
  'calabaza',
  'calabacin',
  'calamares',
  'caldo de ave',
  'caldo de carne',
  'caldo de pescado',
  'caldo de verdura',
  'caldo en cubito',
  'caldo en pastilla',
  'canela en polvo',
  'canela en rama',
  'cangrejo de rio',
  'canola',
  'cantara (pescado)',
  'caqui',
  'caracol',
  'caramelo liquido',
  'caraota',
  'carne de cerdo picada',
  'carne de pollo picada',
  'carne de ternera picada',
  'carne de vacuno',
  'carne de vacuno picada',
  'carne picada',
  'carpa',
  'carrillera de ternera',
  'carrillera de vaca',
  'cava',
  'caviar',
  'cayena',
  'cebolla',
  'cebolla frita',
  'cebolleta',
  'cebollino',
  'centollo',
  'cerdo',
  'cerdo higado',
  'cerdo lomo',
  'cerdo manteca',
  'cerdo paletilla',
  'cereal desayuno',
  'cereal desayuno chocolate',
  'cereza',
  'chabacano',
  'chantarela',
  'chapa (pescado)',
  'chaucha',
  'chayote',
  'chicharron',
  'chile',
  'chile verde',
  'chipiron',
  'chirivia',
  'chistorra',
  'choclo',
  'chocolate',
  'chocolate blanco',
  'chocolate fondant',
  'chocolate negro',
  'chocolate para fondue',
  'chocolate para fundir',
  'chorizo',
  'chuleta de cordero',
  'chuleta de ternera',
  'cilantro',
  'clavo',
  'coco',
  'coco rallado',
  'cogollo',
  'col',
  'col china',
  'col de bruselas',
  'col lombarda',
  'col morada',
  'col rizada',
  'col roja',
  'cola',
  'colapez (gelatina)',
  'coles fermentadas',
  'coliflor',
  'colinabo',
  'colorante alimenticio',
  'congrio',
  'copos de avena',
  'coriandro',
  'costilla de cerdo',
  'costilleja de cerdo',
  'coñac',
  'crema de cacao (licor)',
  'crema de cacao para untar',
  'crema de grosella negra',
  'crema de leche',
  'crema de queso',
  'crema de whisky',
  'crema pastelera',
  'cremor tartaro',
  'cubito de hielo',
  'culantro',
  'cuscus',
  'curcuma',
  'curry rojo',
  'damasco',
  'denton (pescado)',
  'dorada',
  'dulce de boniato',
  'dulce de leche',
  'durazno',
  'datil',
  'edulcorante en polvo',
  'edulcorante liquido',
  'emperador',
  'endibias',
  'endrina',
  'enebro',
  'eneldo',
  'ensaimada',
  'epasote',
  'erizo de mar',
  'escalonia',
  'escarola',
  'escorzonera',
  'esencia de almendra',
  'esencia de canela',
  'esencia de anis',
  'esencia de coco',
  'esencia de cola de mono',
  'esencia de limon',
  'esencia de menta',
  'esencia de pan de pascua',
  'esencia de ron',
  'esencia de rosas',
  'esencia de vainilla',
  'espaguetti',
  'especia',
  'espeton (pescado)',
  'espinaca',
  'esparrago',
  'estornino (pescado)',
  'estragon',
  'extracto de carne',
  'fiambre de pavo',
  'fideos',
  'fideos cortos',
  'fideos de arroz',
  'fideos largos',
  'filete ruso',
  'finas hierbas',
  'fletan (pescado)',
  'focaccia',
  'fogonero',
  'foie de pato',
  'foie-gras',
  'frambuesa',
  'frankfurt',
  'fresa',
  'freson',
  'frijol',
  'frijoles chinos',
  'fructosa',
  'fruta bomba',
  'fruta escarchada',
  'fruta estrella',
  'fruta pan',
  'frutilla',
  'frutos rojos',
  'frutos secos variados',
  'fuet',
  'galleta &quot;digestive&quot;',
  'galleta cucurucho',
  'galleta de canela',
  'galleta de vainilla',
  'galleta dulce',
  'galleta integral',
  'galleta oreo',
  'galleta picada',
  'galleta quely',
  'galleta salada',
  'galleta “maria”',
  'galletas de mantequilla',
  'gallina',
  'gallineta',
  'gallo (ave)',
  'gallo (pescado)',
  'gamba',
  'ganache de chocolate',
  'gaseosa',
  'gasificante',
  'gelatina',
  'germen de trigo',
  'gin',
  'ginebra',
  'golosina',
  'granada',
  'grelos',
  'grosella negra',
  'grosella roja',
  'guanabana',
  'guasca',
  'guayaba',
  'guindas',
  'guindilla',
  'guisante amarillo seco',
  'guisante verde',
  'gula',
  'gumbo',
  'haba',
  'haba de soja',
  'habichuela',
  'hamburguesa',
  'harina',
  'harina blanca',
  'harina con levadura',
  'harina de espelta',
  'harina de fuerza',
  'harina de maiz',
  'harina de reposteria',
  'harina de tempura',
  'harina de trigo',
  'harina fina de maiz',
  'harina floja',
  'harina integral',
  'harina leudante',
  'helado cremoso',
  'helado de almendra',
  'helado de chocolate',
  'helado de fresa',
  'helado de limon',
  'helado de nata',
  'helado de stracciatella',
  'helado de vainilla',
  'hielo',
  'hielo picado',
  'hierba buena',
  'hierba de limon',
  'hierba luisa',
  'hierbabuena',
  'hierbas ibicencas',
  'hierbas provenzales',
  'higado de buey',
  'higado de cerdo',
  'higado de cordero',
  'higado de pollo',
  'higado de ternera',
  'higo',
  'higo chumbo',
  'higo seco',
  'higroforo',
  'hinojo',
  'hoja de roble',
  'hoja de ensalada variada',
  'hoja de limonero',
  'hoja variada de lechuga',
  'hojaldre',
  'hojas ensalada variada',
  'hongo',
  'hueso para caldo',
  'hueso de jamon',
  'huevas de pez',
  'huevo',
  'huevo de avestruz',
  'huevo de codorniz',
  'jalapeño',
  'jamon de york',
  'jamon en tacos',
  'jamon cocido',
  'jamon serrano',
  'jarabe de arce',
  'jengibre',
  'jerez dulce',
  'jerez seco',
  'judion',
  'judia',
  'judia plana',
  'judia verde',
  'jurel',
  'kahlua',
  'kaki',
  'karela',
  'kefir',
  'ketchup',
  'kirsch',
  'kiwi',
  'kuratu',
  'llampuga',
  'lata de atun',
  'langosta',
  'langostino',
  'laurel',
  'lecha (pescado)',
  'leche',
  'leche condensada',
  'leche de almendra',
  'leche de coco',
  'leche desnatada',
  'leche entera',
  'leche evaporada',
  'leche semidesnatada',
  'lechona',
  'lechuga',
  'lechuga iceberg',
  'lechuga romana',
  'levadura',
  'levadura de cerveza',
  'levadura de panaderia',
  'levadura fresca',
  'levadura fresca en polvo',
  'levadura quimica',
  'levadura seca',
  'licor',
  'licor colorante azul',
  'licor de cocuy',
  'licor de cacao',
  'licor de cafe',
  'licor de crema catalana',
  'licor de hierbas',
  'licor de mirto',
  'liebre',
  'limon',
  'llisa (pescado)',
  'lombarda',
  'lomo de cerdo',
  'lomo embuchado',
  'loncha de queso',
  'laminas de lasaña',
  'macarron',
  'magres (pescado)',
  'magro de cerdo',
  'mahonesa',
  'maje (pescado)',
  'malagueta',
  'malojillo',
  'mango',
  'manta (pescado)',
  'manteca',
  'mantequilla light',
  'manzana',
  'mani',
  'marihuana',
  'maria luisa',
  'masa brisa',
  'masa de empanada',
  'masa de hojaldre',
  'masa filo',
  'masa quebrada',
  'mayonesa',
  'maiz dulce',
  'maiz fresco',
  'maiz jojoto',
  'maiz tostado',
  'mejillon',
  'mejillon en conserva',
  'mejorana',
  'melocoton',
  'melocoton en conserva',
  'merengue',
  'merluza',
  'mermelada de albaricoque',
  'mermelada de ciruela',
  'mermelada de frambuesa',
  'mermelada de fresa',
  'mermelada de higos',
  'mermelada de limon',
  'mermelada de melocoton',
  'mermelada de pimiento',
  'mero',
  'mirto rosso',
  'miso',
  'mistela',
  'mollete (pan)',
  'mortadela',
  'morcilla',
  'mostaza',
  'mostaza blanca',
  'mostaza en grano',
  'mostaza negra',
  'mostaza parda',
  'muslo de pollo',
  'musola',
  'nabo amarillo',
  'nacho',
  'nalewka',
  'nann',
  'naranja',
  'naranjada',
  'nata',
  'nata montada',
  'nata para cocinar',
  'nata para montar',
  'navajas',
  'nectarina',
  'negrilla',
  'nuez',
  'nuez de brasil',
  'nuez moscada',
  'necora',
  'niscalo',
  'nispero',
  'oblea',
  'oblea de empanadilla',
  'oliva',
  'onoto',
  'oporto',
  'orejon',
  'oregano',
  'ostra',
  'pajel',
  'paletilla de cerdo',
  'paletilla de ternera',
  'palmito',
  'palo de mallorca',
  'palomo',
  'pan',
  'pan blanco',
  'pan de baguette',
  'pan de chapata',
  'pan de hamburguesa',
  'pan de pita',
  'pan de rosca',
  'pan dürüm',
  'pan integral',
  'pan moreno',
  'pan rallado',
  'pan tostado',
  'panceta',
  'panecillo rustico',
  'panela',
  'papa dulce',
  'papaya',
  'pargo (pescado)',
  'pasta alimenticia',
  'pasta de espirales de colores',
  'pasta filo',
  'pastis',
  'pastrami',
  'patata',
  'pate',
  'pate a las finas hierbas',
  'pechuga de pavo',
  'pechuga de pollo',
  'penne',
  'pepinillo',
  'pepita de chocolate',
  'pera',
  'perdiz',
  'perejil',
  'pescadilla',
  'pescado para caldo',
  'pierna de cordero',
  'pimenton dulce',
  'pimienta',
  'pimienta blanca',
  'pimienta blanca molida',
  'pimienta de jamaica',
  'pimienta dulce',
  'pimienta molida',
  'pimienta negra',
  'pimienta negra molida',
  'pimienta roja',
  'pimienta roja molida',
  'pimienta verde',
  'pimienta verde molida',
  'pimiento asado en lata',
  'pimiento de padron',
  'pimiento italiano',
  'pimiento rojo',
  'pimiento verde',
  'pipa de girasol',
  'placa de lasaña',
  'pluma',
  'pollo',
  'polvo de hornear',
  'polvos para flan',
  'pota',
  'pulpo',
  'pumpernickel',
  'quesito en porciones',
  'queso',
  'queso azul',
  'queso brie',
  'queso camembert',
  'queso cheddar',
  'queso edam',
  'queso emmental',
  'queso feta',
  'queso gorgonzola',
  'queso gouda',
  'queso gruyère',
  'queso havarti',
  'queso mascarpone',
  'queso mozzarella',
  'queso parmesano',
  'queso provolone',
  'queso ricota',
  'queso roquefort',
  'queso ahumado',
  'queso cremoso',
  'queso curado',
  'queso de bufala',
  'queso de cabra',
  'queso de cabrales',
  'queso de tetilla',
  'queso de burgos',
  'queso de oveja',
  'queso en loncha',
  'queso en salmuera',
  'queso fresco',
  'queso maasdam',
  'queso mahones',
  'queso manchego',
  'queso para untar',
  'queso rallado',
  'queso reblochon',
  'queso semicurado',
  'queso tierno',
  'queso tronchon',
  'quinoa',
  'quisquilla - camaron',
  'rabanito',
  'radicheta',
  'raki',
  'rape',
  'ravioli',
  'raya',
  'rebozuelo anaranjado',
  'reduccion de modena',
  'refresco azucarado',
  'refresco de cola',
  'refresco de fresa',
  'refresco de limon con gas',
  'refresco de limon sin gas',
  'refresco de naranja con gas',
  'refresco de naranja sin gas',
  'regaliz',
  'remolacha',
  'repollito de bruselas',
  'repollo',
  'repollo rojo',
  'requeson',
  'requeson 40% materia grasa',
  'requeson no graso',
  'rodaballo',
  'romero',
  'ron',
  'ron malibu',
  'ron miel',
  'ronmiel',
  'rosada',
  'rovellon',
  'rubio (pescado)',
  'ruda',
  'rabano',
  'rucola',
  'rucula',
  'sal',
  'salchica fresca',
  'salchicha de paquete',
  'salchicha frankfurt',
  'salchichon',
  'salmon',
  'salmon ahumado',
  'salsa agridulce',
  'salsa barbacoa',
  'salsa bechamel',
  'salsa bobril',
  'salsa chimichurri',
  'salsa de guacamole',
  'salsa de soja',
  'salsa de tabasco',
  'salsa de tomate',
  'salsa de tomate frito',
  'salsa de tomate triturado',
  'salsa de yogurt',
  'salsa olivada',
  'salsa pesto',
  'salsa perrins',
  'salsa rosa',
  'salsa tikka masala',
  'salsa vinagreta',
  'salsa wasabi',
  'salsa yakisoba',
  'sambuca',
  'sandia',
  'sardina',
  'sardina en conserva',
  'semilla',
  'semilla de amapola',
  'sepia',
  'seta',
  'seta calabaza',
  'seta canterela',
  'sirope de chocolate',
  'sirope de agave',
  'sobre de levadura',
  'soda',
  'soja',
  'solomillo de buey',
  'solomillo de cerdo',
  'solomillo de ternera',
  'sopa estrella',
  'sopa maravilla',
  'sopa tiburon',
  'spaguetti',
  'sucedaneo de cangrejo',
  'suero de leche',
  'suero de mantequilla',
  'sandalo',
  'sesamo',
  'tabasco',
  'tallarin',
  'tamarindo',
  'tamarindo chino',
  'tandoori masala',
  'tapa de dulce',
  'tapioca',
  'ternera',
  'ternera bistec',
  'ternera chuleta',
  'ternera higado',
  'ternera magra',
  'ternera mollejas',
  'ternera riñon',
  'ternera solomillo',
  'tinta de calamar',
  'tocino',
  'tofu',
  'tojo',
  'tomate',
  'tomate cherry',
  'tomate kumato',
  'tomate para ensalada',
  'tomate ramillete',
  'tomate seco',
  'tomate triturado',
  'tomillo',
  'toronja',
  'torta para galiano',
  'tortellini',
  'tortilla de maiz',
  'tortilla japonesa',
  'trompeta de los muertos',
  'trufa',
  'tuna',
  'turron de jijona',
  'te',
  'te de jazmin',
  'te rojo',
  'te verde',
  'uva',
  'uva blanca',
  'uva negra',
  'vainilla',
  'vainilla liquida',
  'ventresca de atun',
  'ventresca en lata',
  'verduras variadas congeladas',
  'verdin',
  'vermout',
  'vieiras',
  'vinagre',
  'vinagre balsamico',
  'vino blanco',
  'vino dulce',
  'vino espumoso',
  'vino moscatel',
  'vino rancio',
  'vino rosado',
  'vino tinto',
  'virutas de chocolate',
  'virutas de colores',
  'vodka',
  'whisky',
  'yerba sagrada',
  'yerba santa',
  'yogourt',
  'yogur de fresa',
  'yogur de limon',
  'yogur de macedonia',
  'yogur de melocoton',
  'yogur de platano',
  'yogur desnatado',
  'yogur griego natural',
  'yogur natural',
  'yogur sabor fresa',
  'yogur sabor limon',
  'yogur sabor macedonia',
  'yogur sabor melocoton',
  'yogur sabor natural',
  'yogur sabor platano',
  'yogurt griego natural',
  'yuca',
  'zafron',
  'zamburiña',
  'zanahoria',
  'zapallito largo',
  'zapallo',
  'zarzamora',
  'zumo de lima',
  'zumo de limon',
  'zumo de manzana',
  'zumo de melocoton',
  'zumo de naranja',
  'zumo de naranja natural',
  'zumo de pera',
  'zumo de piña',
  'zumo de tomate',
  'chocolate (bebida)',
  'ñame',
  'ñoras secas',
  'abadejo',
];
